# Generated by Django 4.2.1 on 2023-06-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20230605_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='default_isbn', max_length=13, unique=True),
        ),
    ]
