# Generated by Django 4.2.1 on 2023-06-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publica_date',
            new_name='publication_yr',
        ),
        migrations.AddField(
            model_name='book',
            name='copies_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
