# Generated by Django 4.2.2 on 2023-06-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileManagement', '0003_remove_user_home_address_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
