# Generated by Django 4.2.1 on 2023-06-04 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='list_owner',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='list_books',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wishlists.book'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
