# Generated by Django 4.2.1 on 2023-06-04 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0002_remove_wishlist_list_owner_wishlist_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='list_books',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wishlists.listbook'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
