# Generated by Django 4.2.1 on 2023-06-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0003_listbook_alter_wishlist_list_books_delete_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='list_books',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='list_books',
            field=models.ManyToManyField(null=True, to='wishlists.listbook'),
        ),
    ]
