# Generated by Django 4.2.1 on 2023-06-05 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishlists', '0004_remove_wishlist_list_books_wishlist_list_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='listbook',
            name='author',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='list_books',
            field=models.ManyToManyField(to='wishlists.listbook'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='owner',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
