# Generated by Django 4.2.1 on 2023-06-05 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0005_listbook_author_alter_wishlist_list_books_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='list_books',
            new_name='books',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='list_title',
            new_name='title',
        ),
    ]
