# Generated by Django 4.2.1 on 2023-06-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdetails', '0002_book_book_description'),
        ('wishlists', '0007_rename_books_wishlist_listbooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='listbooks',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='Book',
            field=models.ManyToManyField(to='bookdetails.book'),
        ),
        migrations.DeleteModel(
            name='ListBook',
        ),
    ]
