# Generated by Django 4.2.1 on 2023-06-27 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookdetails', '0002_book_book_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishlists', '0009_rename_book_wishlist_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='Books',
            field=models.ManyToManyField(blank=True, to='bookdetails.book'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
