# Generated by Django 4.2.1 on 2023-06-27 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileManagement', '0004_alter_user_address_alter_user_email_alter_user_name'),
        ('wishlists', '0010_alter_wishlist_books_alter_wishlist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProfileManagement.user'),
        ),
    ]
