# Generated by Django 4.2.1 on 2023-07-15 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileManagement', '0004_alter_user_address_alter_user_email_alter_user_name'),
        ('wishlists', '0011_alter_wishlist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='owner',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='ProfileManagement.user'),
            preserve_default=False,
        ),
    ]
