# Generated by Django 4.2.1 on 2023-06-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copies_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
