# Generated by Django 4.2.1 on 2023-06-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_publisher_book_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='', max_length=255),
        ),
    ]
