# Generated by Django 4.2.2 on 2023-06-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_description',
            field=models.TextField(null=True),
        ),
    ]
