# Generated by Django 4.2.2 on 2023-06-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdetails', '0002_book_book_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('biography', models.TextField(null=True)),
                ('publisher', models.CharField(max_length=200)),
            ],
        ),
    ]
