# Generated by Django 4.2.2 on 2023-06-25 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookdetails', '0006_alter_book_author'),
    ]

    operations = [
    ]
