# Generated by Django 4.2.2 on 2023-06-25 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookdetails', '0008_auto_20230625_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(
                null=True,
                on_delete=models.CASCADE,
                to='bookdetails.author',
            ),
        ),
    ]
