# Generated by Django 4.2.2 on 2023-06-25 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookdetails', '0010_alter_book_author'),
    ]

    operations = [
    ]
