# Generated by Django 4.2.1 on 2023-06-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdetails', '0012_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=models.TextField(),
        ),
    ]
